name: evidence_domain
description: A new Dart package project.
version: 0.0.1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  evidence_foundation_dart: 0.0.1
  json_annotation: 4.8.1

dev_dependencies:
  json_serializable: 6.7.1
  build_runner: 2.4.6