name: evidence_foundation_flutter
description: A new Flutter package project.
version: 0.1.0

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0