name: evidence_backend
description: A new Dart package project.
version: 0.0.1

environment:
  sdk: '>=3.1.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  evidence_domain: 0.0.1
  evidence_leaf: 0.0.1
  evidence_foundation: 0.0.1
  hive_flutter: 1.1.0