name: evidence_ios_pull_request_actions
run-name: ${{ github.actor }} is running pull request actions
on: [pull_request]
jobs:
  validate-unit-tests:
    runs-on: macos-13
    steps:
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Features tests
        run: swift test --package-path Features
        working-directory: mobile/evidence/ios