name: evidence_ios_pull_request_actions
run-name: ${{ github.actor }} is running pull request actions
on: [pull_request]
jobs:
  validate-unit-tests:
    strategy:
      matrix:
        os: [macos-13]
        swift: ["5.9"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Leaf tests
        run: swift test
        working-directory: mobile/evidence/ios/Leaf
