name: evidence_ios_pull_request_actions
run-name: ${{ github.actor }} is running pull request actions
on: [push]
jobs:
  validate-unit-tests:
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.8"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Run Leaf tests
        run: swift test
        working-directory: mobile/evidence/ios/Leaf