name: evidence_ios_pull_request_actions
run-name: ${{ github.actor }} is running pull request actions
on: [push]
jobs:
  validate-unit-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          xcode-version: '15.0'
      - name: Run Leaf tests
        run: swift test
        working-directory: mobile/evidence/ios/Leaf
        

