name: evidence_ios_pull_request_actions
run-name: ${{ github.actor }} is running pull request actions
on: [pull_request]
jobs:
  validate-unit-tests:
    runs-on: macos-13
    steps:
      - name: Set up Swift
        uses: swift-actions/setup-swift@v1
        with:
          swift-version: "5.9"
      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Leaf tests
        run: xcodebuild \
          -workspace Evidence.xcworkspace \
          -scheme LeafTests \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.0' \
          test
        working-directory: mobile/evidence/ios
